# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 89e528b632918d43045d547eefb103a7a96c381e9a13d340bccf0b342336c777131ed6aaa23ce5e55b33b5b24686bf9fc2bf0740b89883408a90b95ed7982604

test:
  secret_key_base: 0bf4b19d36b13ee56549ac40e5550ef455033150881f8f5347915080edfbe19f1a8d08bad0ad487bb989dbe79312cfec15013d8bd838a021af535cb3992be920

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
